language: go

go:
- 1.12

script: go test -race -v ./...

after_success:
- |
  go test ./... -coverprofile cover.out
  go tool cover -func cover.out | grep total | awk '{print $3}' | xargs -I {} curl \
    --header "Authorization: Token ${TOKEN}" \
    --data value="{}" \
    --data sha="${TRAVIS_COMMIT}" \
    https://seriesci.com/api/repos/seriesci/calc/coverage/combined