
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - run: go test -race -v ./...

      - run:
          name: POST SeriesCI
          command: |
            go test ./... -coverprofile cover.out
            go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}' | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/calc/coverage/values